# roles/install/tasks/install/user.yml
# ====================================
#
# Copying
# -------
#
# Copyright (c) 2022 universe.hashicorp authors and contributors.
#
# This file is part of the *universe.hashicorp* project.
#
# *universe.hashicorp* is a free software project. You can redistribute it
# and/or modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.hashicorp*. If not, see <http://opensource.org/licenses/MIT>.
#
- name: "Do not allow the a user to be in the 'root' group"
  when:
    - "install_system_username != 'root'"
    - "install_system_groupname == 'root'"
  block:
    - name: "Fail on user in group 'root'"
      ansible.builtin.fail:
        msg: "Trying to add user '{{ install_system_username }}' in group '{{ install_system_groupname }}'."
  rescue:
    - name: "Cleaning up"
      ansible.builtin.debug:
        msg: "Cleaning"
      notify: "workdir-cleanup"
      changed_when: true

- name: "Ensure system user and group are present"
  when:
    - "install_system_username != 'root'"
    - "install_system_groupname != 'root'"
  block:
    - name: "Create group"
      ansible.builtin.group:
        name: "{{ install_system_groupname }}"
        system: true
        state: "present"

    - name: "Create user"
      ansible.builtin.user:
        name: "{{ install_system_username }}"
        group: "{{ install_system_groupname }}"
        create_home: false
        home: "{{ install_package_directory.state }}"
        password: "!"
        password_lock: true
        shell: "/sbin/nologin"
        system: true
        state: "present"
  rescue:
    - name: "Cleaning up"
      ansible.builtin.debug:
        msg: "Cleaning"
      notify: "workdir-cleanup"
      changed_when: true
