# galaxy.yaml
# ===========
#
# Copying
# -------
#
# Copyright (c) 2022 universe.hashicorp authors and contributors.
#
# This file is part of the *universe.hashicorp* project.
#
# *universe.hashicorp* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.hashicorp*. If not, see <http://opensource.org/licenses/MIT>.
#
namespace: "universe"
name: "hashicorp"
description: "A set of Ansible roles to manage a Hashicorp stack."
version: "0.1.0-alpha.1"
readme: "README.md"
authors:
  - "See AUTHORS.rst"
license:
  - "MIT"
license_file: "LICENSE.rst"
tags:
  - "consul"
  - "hashicorp"
  - "nomad"
  - "vault"
dependencies:
  "community.general": ">=1.6.0"
  "universe.unix": ">=0.1.0"
repository: "https://github.com/x237net/ansible-universe-hashicorp"
issues: "https://github.com/x237net/ansible-universe-hashicorp/issues"
build_ignore:
  - ".*"
  - "*.lock"
  - "**/.*"
  - "**/*.lock"
  - "changelogs/fragments"
  - "changelogs/fragments/*/**"
  - "pyproject.toml"
