# roles/consul_service/defaults/main.yml
# ======================================
#
# Copying
# -------
#
# Copyright (c) 2022 universe.hashicorp authors and contributors.
#
# This file is part of the *universe.hashicorp* project.
#
# *universe.hashicorp* is a free software project. You can redistribute it
# and/or modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.hashicorp*. If not, see <http://opensource.org/licenses/MIT>.
#
consul_service_system_username: "{{ consul_service_package_name }}"
consul_service_system_groupname: "{{ consul_service_system_username }}"

consul_service_bind_address: "127.0.0.1"
consul_service_cluster_bind_address: "{{ ansible_facts.default_ipv4.address }}"

consul_service_addresses: {}
consul_service_servers: []

consul_service_datacenter: "dc1"
consul_service_primary_datacenter: "{{ consul_service_datacenter }}"

consul_service_dns_port: 8600
consul_service_http_port: 8500
consul_service_https_port: 8501
consul_service_serf_lan_port: 8301
consul_service_serf_wan_port: 8302
consul_service_server_port: 8300

consul_service_start: true
consul_service_ui_enabled: true

consul_service_use_tls: false
