# roles/consul_install/meta/main.yml
# ==================================
#
# Copying
# -------
#
# Copyright (c) 2022 universe.hashicorp authors and contributors.
#
# This file is part of the *universe.hashicorp* project.
#
# *universe.hashicorp* is a free software project. You can redistribute it
# and/or modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.hashicorp*. If not, see <http://opensource.org/licenses/MIT>.
#
dependencies:
  - role: "universe.hashicorp.consul_vars"
  - role: "universe.hashicorp.install"
    vars:
      install_system_username: "{{ consul_vars_system_username }}"
      install_system_groupname: "{{ consul_vars_system_groupname }}"
      install_package_service_content: >-
        {{ lookup('ansible.builtin.template', 'systemd/consul.service.j2') }}
