# roles/nomad_service/tasks/main.yml
# ==================================
#
# Copying
# -------
#
# Copyright (c) 2022 universe.hashicorp authors and contributors.
#
# This file is part of the *universe.hashicorp* project.
#
# *universe.hashicorp* is a free software project. You can redistribute it
# and/or modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.hashicorp*. If not, see <http://opensource.org/licenses/MIT>.
#
- name: "Gather Nomad facts"
  ansible.builtin.include_tasks: "facts.yml"

- name: "Configure Hashicorp Nomad"
  ansible.builtin.include_tasks: "configure.yml"

- name: "Start Hashicorp Nomad client service"
  ansible.builtin.debug:
    msg: "Start service: {{ nomad_vars_systemd_unit }}"
  changed_when: true
  notify: "universe.hashicorp.nomad_handler:client_service_start"
  when:
    - "nomad_service_start"
    - "nomad_service_is_client_mode"

- name: "Start Hashicorp Nomad server service"
  ansible.builtin.debug:
    msg: "Start service: {{ nomad_vars_systemd_client_unit }}"
  changed_when: true
  notify: "universe.hashicorp.nomad_handler:server_service_start"
  when:
    - "nomad_service_start"
    - "nomad_service_is_server"
