# roles/consul_vars/vars/main.yml
# ===============================
#
# Copying
# -------
#
# Copyright (c) 2023 universe/staging authors and contributors.
#
# This file is part of the *universe/staging* project.
#
# *universe/staging* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe/staging*. If not, see <http://opensource.org/licenses/MIT>.
#
consul_vars_package_name: "consul"
consul_vars_systemd_unit: "{{ consul_vars_package_name }}.service"

consul_vars_directory:
  config: "{{ dirs_prefix }}/etc/{{ consul_vars_package_name }}.d"
  install: "{{ dirs_prefix }}/sbin"
  state: "{{ dirs_localstatedir }}/{{ consul_vars_package_name }}"

consul_vars_port:
  dns:
    description: "Used to resolve DNS queries."
    port: "{{ consul_vars_dns_port }}"
    protocols: ["tcp", "udp"]

  http:
    description: "This is used by clients to talk to the HTTP API."
    port: "{{ consul_vars_http_port }}"
    protocols: ["tcp"]

  https:
    description: "This is used by clients to talk to the API over HTTPS."
    port: "{{ consul_vars_https_port }}"
    protocols: ["tcp"]

  serf_lan:
    description: "This is used to handle gossip in the LAN."
    port: "{{ consul_vars_serf_lan_port }}"
    protocol: ["tcp", "udp"]

  serf_wan:
    description: "This is used by servers to gossip over the WAN, to other servers."
    port: "{{ consul_vars_serf_wan_port }}"
    protocols: ["tcp", "udp"]

  server:
    description: "This is used by servers to handle incoming requests from other agents."
    port: "{{ consul_vars_server_port }}"
    protocols: ["tcp"]

consul_vars_tls_ciphers:
  - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
  - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
