# roles/consul_service/vars/main.yml
# ==================================
#
# Copying
# -------
#
# Copyright (c) 2023 universe/staging authors and contributors.
#
# This file is part of the *universe/staging* project.
#
# *universe/staging* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe/staging*. If not, see <http://opensource.org/licenses/MIT>.
#
consul_service_package_name: "consul"
consul_service_systemd_unit: "{{ consul_service_package_name }}.service"

consul_service_directory:
  config: "{{ dirs_prefix }}/etc/{{ consul_service_package_name }}.d"
  install: "{{ dirs_prefix }}/sbin"
  state: "{{ dirs_localstatedir }}/{{ consul_service_package_name }}"

consul_service_port:
  consul_dns:
    description: "Used to resolve DNS queries."
    ports:
      - port: "{{ consul_service_dns_port }}"
        protocol: "tcp"
      - port: "{{ consul_service_dns_port }}"
        protocol: "udp"

  consul_http:
    description: "This is used by clients to talk to the HTTP API."
    ports:
      - port: "{{ consul_service_http_port }}"
        protocol: "tcp"

  consul_https:
    description: "This is used by clients to talk to the API over HTTPS."
    ports:
      - port: "{{ consul_service_https_port }}"
        protocol: "tcp"

  consul_serf_lan:
    description: "This is used to handle gossip in the LAN."
    ports:
      - port: "{{ consul_service_serf_lan_port }}"
        protocol: "tcp"
      - port: "{{ consul_service_serf_lan_port }}"
        protocol: "udp"

  consul_serf_wan:
    description: "This is used by servers to gossip over the WAN, to other servers."
    ports:
      - port: "{{ consul_service_serf_wan_port }}"
        protocol: "tcp"
      - port: "{{ consul_service_serf_wan_port }}"
        protocol: "udp"

  consul_server:
    description: "This is used by servers to handle incoming requests from other agents."
    ports:
      - port: "{{ consul_service_server_port }}"
        protocol: "tcp"

consul_service_tls_ciphers:
  - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
  - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
