# roles/install/meta/main.yml
# ===========================
#
# Copying
# -------
#
# Copyright (c) 2022 universe.hashicorp authors and contributors.
#
# This file is part of the *universe.hashicorp* project.
#
# *universe.hashicorp* is a free software project. You can redistribute it
# and/or modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.hashicorp*. If not, see <http://opensource.org/licenses/MIT>.
#
dependencies:
  - role: "universe.unix.dirs"

  - role: "universe.unix.package_install"
    vars:
      package_install: "unzip"

  - role: "universe.unix.gpg_import"
    vars:
      gpg_import_content: >-
        {{ lookup('ansible.builtin.file', 'gpg/hashicorp.asc') }}

galaxy_info:
  author: "universe.hashicorp authors"
  description: >-
    Fetch and install any package provided by Hashicorp at
    releases.hashicorp.com.
  license: "MIT"
  min_ansible_version: "2.15.0"
