# roles/nomad_service/vars/main.yml
# =================================
#
# Copying
# -------
#
# Copyright (c) 2022 universe.hashicorp authors and contributors.
#
# This file is part of the *universe.hashicorp* project.
#
# *universe.hashicorp* is a free software project. You can redistribute it
# and/or modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.hashicorp*. If not, see <http://opensource.org/licenses/MIT>.
#
nomad_service_is_client_mode: >-
  {{ nomad_service_is_user_client | default(nomad_service_is_client, true) }}

nomad_service_directory_config: >-
  {{ nomad_vars_directory.config }}/{{ nomad_service_is_client_mode | ternary('client.d', 'server.d') }}
nomad_service_api_address: >-
  {{ nomad_service_use_tls | ternary('https', 'http') }}://{{ nomad_bind_address | default('127.0.0.1') }}:{{ nomad_vars_port_http }}
