# roles/install/tasks/main.yml
# ============================
#
# Copying
# -------
#
# Copyright (c) 2022 universe.hashicorp authors and contributors.
#
# This file is part of the *universe.hashicorp* project.
#
# *universe.hashicorp* is a free software project. You can redistribute it
# and/or modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.hashicorp*. If not, see <http://opensource.org/licenses/MIT>.
#
- name: "Collect facts for package {{ install_package_name }} "
  ansible.builtin.include_tasks: "facts.yml"

- name: "Target package information"
  ansible.builtin.debug:
    msg: "Targeting {{ install_package_name }} v{{ install_package_version }}"

- name: "Download package {{ install_package_name }}"
  ansible.builtin.include_tasks: "download.yml"
  when: >-
    (
      system_package.version
      and install_package_version not in system_package.version
    )
    or not system_package.exists
    or install_force

- name: "Install {{ install_package_name }}"
  ansible.builtin.include_tasks: "install/main.yml"

- name: "Cleaning up"
  ansible.builtin.debug:
    msg: "Cleaning"
  notify: "workdir-cleanup"
  changed_when: true
